# Site Settings
title: Alex Barsom
tagline: Composer
email: alexbarsom123@gmail.com
description: >
  Official site of composer Alex Barsom
baseurl: "/alexbarsom1"
url: "https://alexbarsom.github.io"
permalink: pretty
favicon: /composerwebsitefavicon.png
#hide_share_buttons: true
#theme_color: '#eeeeee'
#fixed_navbar: top

paginate: 5
paginate_path: "/blog/page:num"

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  # shortname: my_disqus_shortname


plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

#google_analytics: UA-code-here

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "C.S. Rhymes"
      layout: post
      image: https://via.placeholder.com/1200x800
      show_sidebar: true

markdown: kramdown
highlighter: rouge

footer_menu: example_footer_menu

collections:
  Works: 
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false